language: java

sudo: false

cache:
 directories:
   - C:\Users\Karolina\.m2

before_install:
  - export MAVEN_OPTS="-Xmx512M $MAVEN_OPTS"

before_script:
  - unset GEM_PATH GEM_HOME IRBRC JRUBY_OPTS
  - export PATH="`pwd`/bin:$PATH"
  - echo $HOME
  - echo $JAVA_OPTS
  - echo $MAVEN_OPTS

jdk:
  - oraclejdk8

os:
  - windows
install: true
script:
  - cd pingPong && mvn test